name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test build
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi
          echo "Build successful - dist directory exists"

      - name: Bump version
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "patch" ]; then
            npm run version:patch
          elif [ "${{ github.event.inputs.release_type }}" = "minor" ]; then
            npm run version:minor
          elif [ "${{ github.event.inputs.release_type }}" = "major" ]; then
            npm run version:major
          fi

      - name: Generate Changelog
        id: changelog
        run: |
          # Get the new version from package.json
          NEW_VERSION=$(node -p 'require("./package.json").version')
          
          # Get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag, get all commits
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            # Get commits since the previous tag
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges $PREVIOUS_TAG..HEAD)
          fi
          
          # Create changelog
          CHANGELOG="## What's Changed in v$NEW_VERSION
          
          $COMMITS
          
          ## Installation
          
          You can install this as a PWA on supported devices or use it directly in your browser.
          
          ## Full Changelog
          
          See the [commit history](https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...v$NEW_VERSION) for all changes."
          
          # Save to file for the next step
          echo "$CHANGELOG" > CHANGELOG.md
          
          # Also output for GitHub Actions
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create tag and push
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          git add package.json package-lock.json
          git add CHANGELOG.md
          git commit -m "chore: bump version to $VERSION"
          git tag "v$VERSION"
          git push origin main
          git push origin "v$VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(node -p 'require("./package.json").version')
          release_name: Release v$(node -p 'require("./package.json").version')
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.changelog }}

